---
  - hosts: hosts
    vars:
      site_name: staging.laravel-starter.com
    roles:
      - role: geerlingguy.mysql # only on mysql
      - nginx
      - phpbrew
      - role: oefenweb.yarn
      - role: geerlingguy.pip
      - role: geerlingguy.supervisor
      - role: geerlingguy.composer
      - role: moviedo.nvm
        nvm_user: ubuntu
        nvm_version: "v0.35.2"
        nvm_node_version: "12.15.0"
