version: '2.1'

services:
  php7:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    command:
      >
        bash -i -c -e
        "
        cd app;
        composer install;
        php artisan migrate;
        yarn install;
        php artisan serve --host 0.0.0.0
        "

  db:
    image: mysql:5.7 # or mariadb
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: "exit 0"

  phpmyadmin:
    image:
      phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "${PHP_MYADMIN_PORT}:80"

volumes:
  data: {}
