version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        cmd: ["/bin/bash"]

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-rubygem-{{ checksum "Gemfile.lock" }}

      - run:
          name: Copy environment variables
          command: |
            cp .env.example .env

      - save_cache:
          key: dependency-cache-rubygem-{{ checksum "Gemfile.lock" }}
          paths:
            - /var/lib/gems
            - /usr/local/bin/cap
            - /usr/local/bin/capify
  deploy:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        cmd: ["/bin/bash"]
    steps:
      - checkout
      - run:
          name: Copy environment variables
          command: |
            cp .env.example .env
      - deploy:
          command: |
            gem install bundler -v 1.17.3
            bundle check || bundle install

            echo "current branch is ${CIRCLE_BRANCH}"
            echo "current tag is ${CIRCLE_TAG}"

            if [[ -n "${CIRCLE_TAG}" ]]; then
              CI_BRANCH="${CIRCLE_TAG}" cap production deploy --trace
            elif [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              CI_BRANCH=master cap staging deploy --trace
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: master
