---
- name: (PHPMYADMIN) Installing dbconfig-common
  package:
    name: dbconfig-common
    state: latest

- name: (PHPMYADMIN) Pre-configure database
  template:
    src: dbconfig-common.conf
    dest: /etc/dbconfig-common/phpmyadmin.conf
    owner: root
    group: root
    mode: 0600

- name: Create folder for deployment if it does not exist
  file:
    path: /opt/www/phpmyadmin
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name:  (PHPMYADMIN) Installing phpmyadmin
  unarchive:
    src: https://files.phpmyadmin.net/phpMyAdmin/5.0.4/phpMyAdmin-5.0.4-all-languages.tar.gz
    dest: /opt/www/phpmyadmin
    extra_opts: [--strip-components=1]
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    remote_src: yes

- name: (PHPMYADMIN) Create config
  template:
    src: config.inc.php
    dest: /opt/www/phpmyadmin
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    force: true


# - name: (PHPMYADMIN) Installing phpmyadmin
#   package:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - phpmyadmin
#     - dnsutils
