apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../bases/
patchesStrategicMerge:
  - backend/config-map-patch.yaml
  - system/aws-auth-patch.yaml
patches:
  - path: backend/ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: backend
  - path: backend/deployment-phpmyadmin-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: phpmyadmin-deployment
