---
- name: Install nginx using apt
  apt:
    name: nginx

- name: Remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Copy nginx config
  template:
    src: templates/nginx.conf
    dest: "/etc/nginx/nginx.conf"
  notify:
  - restart nginx

- name: Copy nginx config for site
  template:
    src: templates/site.conf
    dest: "/etc/nginx/sites-enabled/{{ site_name }}"
  notify:
  - restart nginx

- name: Create folder for deployment if it does not exist
  file:
    path: /opt/www
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
