---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: checkout phpbrew
  git: repo=https://github.com/phpbrew/phpbrew.git dest=/opt/phpbrew-bin

- name: make a link to phpbrew
  file: state=link src=/opt/phpbrew-bin/phpbrew dest=/usr/bin/phpbrew

- name: install PHP CLI interpreter
  apt: name=php-cli state=present

- name: Install system packages
  apt: name={{ item }} state=present
  with_items: "{{ phpbrew_requirements }}"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: run phpbrew init
  shell: phpbrew init
  become_user: ubuntu


- name: create a PHP environment with phpbrew
  shell: phpbrew install {{ phpbrew_php_version }} {{ phpbrew_php_variants }} creates="/home/ubuntu/.phpbrew/php/php-{{ phpbrew_php_version }}/bin/php"
  become_user: ubuntu

- name: install PHP extensions
  shell: bash -c "source /home/ubuntu/.phpbrew/bashrc && phpbrew switch php-{{ phpbrew_php_version }} && phpbrew ext install {{ item.name }}" creates="/home/ubuntu/.phpbrew/php/php-{{ phpbrew_php_version }}/var/db/{{ item.config }}"
  become_user: ubuntu
  with_items:
    - { name: gd, config: "gd.ini" }
    - { name: curl, config: "curl.ini" }
  notify: "restart php-fpm"

- name: Update bashrc for PythonBrew for foo user
  lineinfile:
    dest: /home/ubuntu/.bashrc
    line: "source ~/.phpbrew/bashrc"
    owner: ubuntu

- name: put php-fpm.conf
  template: src=php-fpm.conf dest="/home/ubuntu/.phpbrew/php/php-{{ phpbrew_php_version }}/etc/php-fpm.conf"
  become_user: ubuntu
  when: "phpbrew_enable_php_fpm_service"
  notify: "restart php-fpm"

- name: Give insecure permissions to an existing file
  file:
    path: /home/ubuntu/.phpbrew/php/php-{{ phpbrew_php_version }}/var/run/php-fpm.sock
    owner: root
    group: root
    mode: '1777'

- name: set timezone in php.ini
  become_user: ubuntu
  lineinfile:
    dest: "/home/ubuntu/.phpbrew/php/php-{{ phpbrew_php_version }}/etc/php.ini"
    regexp: "^;date.timezone ="
    line: "date.timezone = \"{{ timezone }}\""
  when: "timezone|default(False) != False"
  notify: "restart php-fpm"

- name: put php-fpm unit file
  template: src=php-fpm.service dest="/etc/systemd/system/php-fpm{{ phpbrew_php_version | regex_replace('\\.', '_') }}.service" owner=root group=root mode=0644
  when: phpbrew_enable_php_fpm_service and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: enable php-fpm service
  service: name="php-fpm{{ phpbrew_php_version | regex_replace('\\.', '_') }}" enabled=yes state=started
  when: phpbrew_enable_php_fpm_service and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
